<?php


namespace app\components;


use yii\base\Widget;
use app\models\Category;

class MenyWidget extends Widget
{
    public $tpl;
    public $data; // данные
    public $tree; // дерево из данных
    public $menuHtml; // шаблон с данными

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!$this->tpl) {
            $this->tpl = 'menu';
        }

        $this->tpl .= '.php';
    }

    public function run()
    {
        $this->data = Category::find()->indexBy('id')->asArray()->all();
        debug($this->data);
        return $this->tpl;
    }
}