<?php


namespace app\components;


use yii\base\Widget;
use app\models\Category;
use \Yii;

class MenyWidget extends Widget
{
    public $tpl;
    public $data; // данные
    public $tree; // дерево из данных
    public $menuHtml; // шаблон с данными

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!$this->tpl) {
            $this->tpl = 'menu';
        }

        $this->tpl .= '.php';
    }

    public function run()
    {
        // проверяем кеш

        if ( $menu = Yii::$app->cache->get('menu')) {
            return $menu;
        }

        $this->data = Category::find()->indexBy('id')->asArray()->all();
        $this->tree = $this->getTree();
        $this->menuHtml = $this->getMenuHtml($this->tree);
        Yii::$app->cache->set('menu', $this->menuHtml, 60);

        return $this->menuHtml;
    }

    public function getTree()
    {
        $tree = [];
        foreach ($this->data as $id => &$node) {
            if (!$node['parent_id']) {
                $tree[$node['id']] = &$node;
            } else {
                $this->data[$node['parent_id']]['childs'][$node['id']] = &$node;
            }
        }
        return $tree;
    }

    public function getMenuHtml($tree)
    {
        $str = '';
        foreach ($tree as $category) {
            $str .= $this->catToTemplate($category);
        }
        return $str;
    }

    public function catToTemplate($category)
    {
        ob_start();
        require __DIR__ . '/menu_tpl/' .$this->tpl;
        return ob_get_clean();
    }

}